services:
  anx-calibre-manager:
    build: .
    container_name: anx-calibre-manager
    ports:
      - "5000:5000"
    volumes:
      - ./data/config:/config
      - ./data/webdav:/webdav
      - ./data/audiobooks:/audiobooks
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - GUNICORN_WORKERS=2 # 可选：自定义 Gunicorn worker 进程数量
      - SECRET_KEY=your_super_secret_key # 请务必修改此项
      - CALIBRE_URL=http://your-calibre-server-ip:8080
      - CALIBRE_USERNAME=your_calibre_username
      - CALIBRE_PASSWORD=your_calibre_password
      - CALIBRE_DEFAULT_LIBRARY_ID=Calibre_Library # 可选：Calibre 默认书库 ID
      - CALIBRE_ADD_DUPLICATES=false # 可选：是否允许上传重复书籍
      - REQUIRE_INVITE_CODE=true # 可选：默认需要邀请码注册，设置为 false 则禁用
      - SMTP_SERVER=
      - SMTP_PORT=587
      - SMTP_USERNAME=
      - SMTP_PASSWORD=
      - SMTP_ENCRYPTION=ssl
      # --- Audiobook Generation Settings (Optional) ---
      - DEFAULT_TTS_PROVIDER=edge_tts # Default TTS provider: edge_tts or openai_tts
      - DEFAULT_TTS_VOICE=en-US-AriaNeural # Default TTS voice
      - DEFAULT_TTS_RATE=+0% # Default TTS rate, e.g., +10%
      - DEFAULT_TTS_SENTENCE_PAUSE=650 # Default sentence pause in milliseconds
      - DEFAULT_TTS_PARAGRAPH_PAUSE=900 # Default paragraph pause in milliseconds
      - DEFAULT_OPENAI_API_KEY= # Required if using openai_tts
      - DEFAULT_OPENAI_API_BASE_URL=https://api.openai.com/v1 # Custom base URL for OpenAI-compatible APIs
      - DEFAULT_OPENAI_API_MODEL=tts-1 # OpenAI model for TTS
    restart: unless-stopped