blank_issues_enabled: false
contact_links:
  - name: Ask a question / 提问
    url: https://github.com/ptbsare/anx-calibre-manager/discussions/new?category=q-a
    about: Please ask and answer questions here. / 请在这里提问和回答问题。